services:
  - type: web
    name: messenger-server
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SERVER_PORT
        value: 10000
      - key: CLIENT_URL
        fromService:
          type: web
          name: messenger-client
          property: host
    autoDeploy: false